apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-taint-service
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taint-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-taint-view
subjects:
- kind: ServiceAccount
  name: create-taint-service
  namespace: default
roleRef:
  kind: ClusterRole
  name: taint-creator
  apiGroup: rbac.authorization.k8s.io
~
