apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-configmap-service
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-lister
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-configmap-view
subjects:
- kind: ServiceAccount
  name: list-configmap-service
  namespace: default
roleRef:
  kind: ClusterRole
  name: configmap-lister
  apiGroup: rbac.authorization.k8s.io