apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-cronjob-service
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-creator
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-cronjob-view
subjects:
- kind: ServiceAccount
  name: create-cronjob-service
  namespace: default
roleRef:
  kind: ClusterRole
  name: cronjob-creator
  apiGroup: rbac.authorization.k8s.io